### ISSUE TITLE
can't get it to color anything...

### ISSUE THREAD

**Issue by fragolinux** [anordal/shellharden#38] opened 2021-02-07 10:46 UTC
hi, i tried both the monolithic bin from releases, and the cargo install on ubuntu, both just color the comments if called passing a bash script as argument (and doing the variable escaping etc etc, yes), but no syntax highlight in fg or mark of the "changing" parts in bg color... any help?

**Comment by anordal** [comment] 2021-02-07 19:53
Use a terminal that supports 24-bit color, such as konsole.

Duplicate of #34.

**Closed as completed** 2021-02-07 19:56 UTC
