### ISSUE TITLE
parsing error?

### ISSUE THREAD

**Issue by greg-minshall** [anordal/shellharden#59] opened 2024-08-30 14:19 UTC
hi.  i'm running 4.3.1 on arch linux.  a file with just the following lines in it
````
    if [[ $option =~ (\[((no|dont)-?)\]). ]]; then
        option2=${option/"${BASH_REMATCH[1]}"/}
        option2=${option2%%[<{().[]*}
        options+=("${option2/=*/=}")
        option=${option/"${BASH_REMATCH[1]}"/"${BASH_REMATCH[2]}"}
    fi
````
gets
````
x.sh: Unexpected end of file
The file's end was reached without closing all sytactic scopes.
Either, the parser got lost, or the file is truncated or malformed.
````

cheers.

**Comment by anordal** [comment] 2024-08-30 16:29
The parser counts curly braces in variable expansions to handle recursion (#39).
The problem is the different number of opening and closing curly braces in this variable substitution:

```bash
${option2%%[<{().[]*}
```

I guess the string "[<{().[]" is to be taken literally in this case.
In my defense, GitHub's syntax highlighter gives up after the second opening curly brace.

I need to revisit that recursion handling and see if not counting `${` and `}` instead would be more correct.

Thanks for reporting.

**Comment by greg-minshall** [comment] 2024-08-31 04:00
you're welcome.  thanks for the explanation -- i was curious if it would be the extra square bracket or the curly brace.  and, thanks for the tool!

**Closed as completed** 2024-09-01 09:51 UTC
